### PR TITLE
Fix user creation form redirection

### LINKED ISSUE #3648: [BUG] user create: without a passwort -> redirect to start page
**Describe the bug**
When I try to create a user without a password, than I will redirected to the start page without an error and without creating a new user

**To Reproduce**
go to "create new user",
input a user name (1), leave the password empty (2) and klick "submit" (3)
image

**Expected behavior**
a hint, that the password input field is empty. 
Do not expect a redirect to the start page

**Environment information (please complete the following information):**
 - Browser: Firefox 88
 - FreshRSS version: 1.18.0

### PR DESCRIPTION
**Pull request by aledeg**
Changes proposed in this pull request:

- Fix user creation form redirection

How to test the feature manually:

1. Try to create a user without a password from the user page.
2. Check there is an error displayed and you're still on the user management page.

Pull request checklist:

- [x] clear commit messages
- [x] code manually tested
- [ ] unit tests written (optional if too hard)
- [ ] documentation updated

[Additional information can be found in the documentation](https://github.com/FreshRSS/FreshRSS/tree/edge/docs/en/developers/04_Pull_requests.md).

Before, when there was an error during the user creation process, the user was
always redirected to the same page no matter where the creation process was
initiated (registration or creation by an admin). Thus, there were no error
messages displayed when something went bad during the creation process by an
admin.
Now, the origin of the user creation has been added to the form to be able to
redirect the user to the proper page.

### CODE REVIEW

File: app/Controllers/userController.php [hunk 1]
```diff
@@ -287,25 +287,29 @@ public function createAction() {
 			$new_user_name = Minz_Request::param('new_user_name');
 			$email = Minz_Request::param('new_user_email', '');
 			$passwordPlain = Minz_Request::param('new_user_passwordPlain', '', true);
+			$badRedirectUrl = [
```
Comment (Alkarex) [inline app/Controllers/userController.php:290]: Did you check whether there is no other call to this endpoint?
Maybe it would be good to have default values `[ 'c' => 'auth', 'a' => 'register' ]` if some of the `origin*` parameters are missing

Comment (aledeg) [reply app/Controllers/userController.php:290]: I have not. But I'll add default values.

File: app/views/auth/register.phtml [hunk 2]
```diff
@@ -3,6 +3,8 @@
 
 	<form method="post" action="<?= _url('user', 'create') ?>">
 		<input type="hidden" name="_csrf" value="<?= FreshRSS_Auth::csrfToken() ?>" />
+		<input type="hidden" name="originController" value="<?= Minz_Request::controllerName(); ?>" />
```
Comment (Alkarex) [inline app/views/auth/register.phtml]:
```suggestion
		<input type="hidden" name="originController" value="<?= Minz_Request::controllerName() ?>" />
```

I do not think it makes a difference for now, but the short syntax for echo does not take a final semicolon https://php.net/echo

Comment (aledeg) [reply app/views/auth/register.phtml]: I'll fix that

**Comment by aledeg** [comment]
@Alkarex I've addressed your remarks.
