### PR TITLE
Fix label management

### LINKED ISSUE #3815: [BUG] rename a non existing category leads to a white page
grafik

**To Reproduce**
1. Go to subscription management -> label management 
2. (remove all categories, if you have some)
2. Click on 'rename'
3. See error: a white page appears

**Expected behavior**
a error message

**Environment information (please complete the following information):**
 - FreshRSS version: 1.18.1

**additional information**
in development mode following error message is shown on the "white page"
`Fatal error: Uncaught Error: Call to a member function name() on null in /xxx/app/Controllers/tagController.php:111 Stack trace: #0 /xxx/lib/Minz/Dispatcher.php(119): FreshRSS_tag_Controller->renameAction() #1 /xxx/lib/Minz/Dispatcher.php(47): Minz_Dispatcher->launchAction() #2 /xxx/lib/Minz/FrontController.php(81): Minz_Dispatcher->run() #3 /xxx/p/i/index.php(57): Minz_FrontController->run() #4 {main} thrown in /xxx/app/Controllers/tagController.php on line 111`

### PR DESCRIPTION
**Pull request by math-GH**
Closes #3815

After:
grafik

Changes proposed in this pull request:
- when no labels: rename and remove inputs are disabled and buttons are hidden

How to test the feature manually:

1. go to label management page
2. delete all labels
3. disabled rename and remove forms

Pull request checklist:
- [x] clear commit messages
- [x] code manually tested

### CODE REVIEW

**Comment by math-GH** [comment]
Fixed also: cannot create an empty label anymore

File: app/Controllers/tagController.php [hunk 1]
```diff
@@ -90,7 +90,7 @@ public function addAction() {
 
 		$name = Minz_Request::param('name');
 		$tagDAO = FreshRSS_Factory::createTagDao();
-		if (null === $tagDAO->searchByName($name)) {
+		if (null === $tagDAO->searchByName($name) && strlen($name) > 0) {
```
Comment (Alkarex) [inline app/Controllers/tagController.php]: If probably makes sense to test the variable before using it rather than after
```suggestion
		if (strlen($name) > 0 && null === $tagDAO->searchByName($name)) {
```

File: app/views/tag/index.phtml [hunk 2]
```diff
@@ -13,7 +13,7 @@
 		<div class="form-group">
 			<label class="group-name" for="new_label_name"><?= _t('sub.tag.name') ?></label>
 			<div class="group-controls">
-				<input id="new_label_name" name="name" type="text" autocomplete="off"/>
+				<input id="new_label_name" name="name" type="text" autocomplete="off" required/>
```
Comment (Alkarex) [inline app/views/tag/index.phtml]:
```suggestion
				<input id="new_label_name" name="name" type="text" autocomplete="off" required="required" />
```

File: app/views/tag/index.phtml [hunk 3]
```diff
@@ -25,12 +25,17 @@
 	</form>
 
 	<h2><?= _t('sub.title.rename_label') ?></h2>
+	<?php
+	$disabled = '';
+	if (count($this->tags) < 1) {
+		$disabled = ' disabled';
```
Comment (Alkarex) [inline app/views/tag/index.phtml]:
```suggestion
		$disabled = ' disabled="disabled"';
```

**Review by Alkarex — CHANGES_REQUESTED** [review]
Minor suggestions

**Review by Alkarex — APPROVED** [review]

**Comment by Alkarex** [comment]
I will try to test all those PRs at once tomorrow

**Review by Alkarex — APPROVED** [review]
