### PR TITLE
Fix DB lock bug during refresh (MariaDB)

### LINKED ISSUE #3552: SQL error updateTTL when importing tt-rss opml [BUG]
**Describe the bug**
Newly installed 1.80 via cPanel, imported my (less than 100) feeds i prevoiusly exported via an outdated (cPanel) tt-rss instance

feeds don't automatically update. Single feeds when forced update do show new items. Trying to force a complete feed refresh doesn't work

looking at logs there is an error:

2021-03-22 10:23:59
SQL error updateTTL 2: Duplicate column name 'ttl' ALTER TABLE `_feed` ADD COLUMN ttl INT NOT NULL DEFAULT 0
2021-03-22 10:23:59
SQL warning updateTTL 1: Deadlock found when trying to get lock; try restarting transaction UPDATE `_feed` SET ttl=:new_value WHERE ttl=:old_value
2021-03-22 10:23:58
SQL error updateTTL 2: Duplicate column name 'ttl' ALTER TABLE `_feed` ADD COLUMN ttl INT NOT NULL DEFAULT 0
2021-03-22 10:23:58
SQL warning updateTTL 1: Deadlock found when trying to get lock; try restarting transaction UPDATE `_feed` SET ttl=:new_value WHERE ttl=:old_value

**Environment information (please complete the following information):**
cPanel

**Additional context**
I suspect there's an issue with updating imported tt-rss exported feeds.

### PR DESCRIPTION
**Pull request by Alkarex**
#fix https://github.com/FreshRSS/FreshRSS/issues/3552

### CODE REVIEW

File: app/Controllers/feedController.php [hunk 1]
```diff
@@ -24,7 +24,6 @@ public function firstAction() {
 				Minz_Error::error(403);
 			}
 		}
-		$this->updateTTL();
```
Comment (Alkarex) [inline app/Controllers/feedController.php:27]: Not really needed, and was creating a dead-lock.

**Comment by Alkarex** [comment]
Merging, as important and straightforward
