### PR TITLE
Fix CLI api_password

### LINKED ISSUE #3177: FreshRSS error: unknown options: api_password
I am trying to create a new user by the CLI. I'm surprised to get an error: `FreshRSS error: unknown options: api_password`.

When I'm looking at the [documentation](https://github.com/FreshRSS/FreshRSS/tree/5389dd5ddb4a164d0df5e2144442b136ec4fe947/cli#commands), I can see that the option should exist:

```bash
./cli/create-user.php --user username [ --password 'password' --api_password 'api_password' --language en --email user@example.net --token 'longRandomString' --no_default_feeds --purge_after_months 3 --feed_min_articles_default 50 --feed_ttl_default 3600 --since_hours_posts_per_rss 168 --max_posts_per_rss 400 ]
```

Is it linked in a way or another to merge request #2675?

### PR DESCRIPTION
**Pull request by Alkarex**
#fix https://github.com/FreshRSS/FreshRSS/issues/3177
Fix regression from https://github.com/FreshRSS/FreshRSS/pull/2675

### CODE REVIEW

File: cli/_update-or-create-user.php [hunk 1]
```diff
@@ -22,7 +23,7 @@
 
 if (!validateOptions($argv, $params) || empty($options['user'])) {
 	fail('Usage: ' . basename($_SERVER['SCRIPT_FILENAME']) .
-		" --user username ( --password 'password'" .
+		" --user username ( --password 'password' --api_password 'api_password'" .
 		" --language en --email user@example.net --token 'longRandomString'" .
 		($isUpdate ? '' : '--no_default_feeds') .
```
Comment (oupala) [inline cli/_update-or-create-user.php]:
```suggestion
		($isUpdate ? '' : ' --no_default_feeds') .
```

**Review by oupala — CHANGES_REQUESTED** [review]
to fix the typo in inlined documentation
