### PR TITLE
PHP8: SimplePie wrong use of isset

### LINKED ISSUE #3401: Uncaught TypeError: ceil(): Argument #1 ($num) must be of type int|float, string given
I'm on 1.17.1-dev, docker: 

```
freshrss       | FreshRSS[164]: SimplePie GET http://podcast.hr2.de/derTag/podcast.xml
freshrss       | PHP Fatal error:  Uncaught TypeError: ceil(): Argument #1 ($num) must be of type int|float, string given in /var/www/FreshRSS/lib/SimplePie/SimplePie/Item.php:2871
freshrss       | Stack trace:
freshrss       | #0 /var/www/FreshRSS/lib/SimplePie/SimplePie/Item.php(2871): ceil()
freshrss       | #1 /var/www/FreshRSS/lib/SimplePie/SimplePie/Item.php(1062): SimplePie_Item->get_enclosures()
freshrss       | #2 /var/www/FreshRSS/lib/SimplePie/SimplePie/Item.php(937): SimplePie_Item->get_enclosure()
freshrss       | #3 /var/www/FreshRSS/app/Models/Feed.php(371): SimplePie_Item->get_permalink()
freshrss       | #4 /var/www/FreshRSS/app/Controllers/feedController.php(354): FreshRSS_Feed->loadEntries()
freshrss       | #5 /var/www/FreshRSS/app/Controllers/feedController.php(548): FreshRSS_feed_Controller::actualizeFeed()
freshrss       | #6 /var/www/FreshRSS/lib/Minz/Dispatcher.php(119): FreshRSS_feed_Controller->actualizeAction()
freshrss       | #7 /var/www/FreshRSS/lib/Minz/Dispatcher.php(47): Minz_Dispatcher->launchAction()
freshrss       | #8 /var/www/FreshRSS/lib/Minz/FrontController.php(81): Minz_Dispatcher->run()
freshrss       | #9 /var/www/FreshRSS/app/actualize_script.php(75): Minz_FrontController->run()
freshrss       | #10 {main}
freshrss       |   thrown in /var/www/FreshRSS/lib/SimplePie/SimplePie/Item.php on line 2871
```

### PR DESCRIPTION
**Pull request by Alkarex**
#fix https://github.com/FreshRSS/FreshRSS/issues/3401 (crash with PHP 8+)

`ceil()` crashes in PHP8+ in case of invalid input such as empty string.
`intval()` fixes the problem with almost identical behaviour than `ceil()` in PHP7- (except for floating point values)

#fix FreshRSS/FreshRSS#3401 (crash with PHP 8+)

Example with feed http://podcast.hr2.de/derTag/podcast.xml

```xml
<enclosure url="https://mp3podcasthr-a.akamaihd.net:443/mp3/podcast/derTag/derTag_20210129_87093232.mp3"
length="" type="audio/mpeg"/>
```

`isset("")` passes and then `ceil("")` crashes due to wrong type in PHP8+:

```
Uncaught TypeError: ceil(): Argument #1 ($num) must be of type
int|float, string given in ./SimplePie/SimplePie/Item.php:2871
```

### CODE REVIEW

**Comment by Alkarex** [comment]
Patch sent upstream https://github.com/simplepie/simplepie/pull/670

File: lib/SimplePie/SimplePie/Item.php [hunk 1]
```diff
@@ -2862,11 +2862,11 @@ public function get_enclosures()
...
 					$url = $this->sanitize($enclosure[0]['attribs']['']['url'], SIMPLEPIE_CONSTRUCT_IRI, $this->get_base($enclosure[0]));
-					if (isset($enclosure[0]['attribs']['']['type']))
+					if (!empty($enclosure[0]['attribs']['']['type']))
 					{
 						$type = $this->sanitize($enclosure[0]['attribs']['']['type'], SIMPLEPIE_CONSTRUCT_TEXT);
 					}
-					if (isset($enclosure[0]['attribs']['']['length']))
+					if (!empty($enclosure[0]['attribs']['']['length']))
 					{
 						$length = ceil($enclosure[0]['attribs']['']['length']);
```
Comment (Alkarex) [inline lib/SimplePie/SimplePie/Item.php]: Here was the actual crash with PHP8+

**Comment by Alkarex** [comment]
Merged upstream
