### PR TITLE
Curlopt fixes

### LINKED ISSUE #3378: minor CURLOPT problem
I was testing the CURLOPT merge and found a really dumb flaw. I really should've seen it earlier.

https://github.com/FreshRSS/FreshRSS/blob/ee175dd6169a016fc898fac62d046e22c205dec0/lib/lib_rss.php#L190-L195

line 192 should obviously be:
```
$curl_options[$co] = $v; 
```

### PR DESCRIPTION
**Pull request by printfuck**
Closes #3378

Pull request checklist:

- [ ] clear commit messages
- [x ] code manually tested
- [ ] documentation updated

Everything else should be OK.

### CODE REVIEW

File: lib/lib_rss.php [hunk 1]
```diff
@@ -189,7 +189,7 @@ function customSimplePie($attributes = array()) {
 	}
 	if (!empty($attributes['curl_params']) && is_array($attributes['curl_params'])) {
 		foreach ($attributes['curl_params'] as $co => $v) {
-			curl_setopt($ch, $co, $v);
+			$curl_options[$co] = $v;
```
Comment (Alkarex) [inline lib/lib_rss.php:192]: As a future improvement, could you please check whether a version without loop and using e.g. `array_merge()` could do the job?

Comment (printfuck) [reply lib/lib_rss.php:192]: I already did, it should work.

Comment (Alkarex) [reply lib/lib_rss.php:192]: We need to double check that the array keys are not modified in a wrong way (I am afraid they would be, with `array_merge`)
