### PR TITLE
Fix #3900 / #3950: main.js incl. update feed shortcut

### LINKED ISSUE #3950: [BUG] main.js broken via PR #3900
**Describe the bug**
main.js is broken via #3900 https://github.com/FreshRSS/FreshRSS/pull/3900#issuecomment-955446934

I found it because the "feed update" shortcut does not work that should be implemented with #3900

### PR DESCRIPTION
**Pull request by math-GH**
Closes #3950 / fixed #3900

Changes proposed in this pull request:
- implemented the logic to run the update button made in #3900

How to test the feature manually:
1. press the shortcut to update the feeds
2. feeds will be updated

Pull request checklist:
- [x] clear commit messages
- [x] code manually tested

### CODE REVIEW

File: p/scripts/main.js [hunk 1]
```diff
@@ -857,6 +857,13 @@ function init_shortcuts() {
 				return false;
 			}
 		}
+		if (k === s.actualize) {
+			const btn = document.getElementById('actualize');
+			if (btn) {
+				btn.click();
+			}
```
Comment (Frenzie) [inline p/scripts/main.js:864]: Why not just call the action directly?

Comment (Frenzie) [reply p/scripts/main.js:864]: I see. I suppose that's fine then, but it might mean it's time to refactor it out. I'll defer to @Alkarex.
https://github.com/FreshRSS/FreshRSS/blob/9326e419e3b90b2db4b6a8531503b710605ac6d4/p/scripts/main.js#L1234-L1286

Comment (Alkarex) [reply p/scripts/main.js:864]: I might have missed a comment. What is your suggestion, @Frenzie ?

Comment (Frenzie) [reply p/scripts/main.js:864]: Conceptually I'd expect these to be separate actions that trigger the same function, rather than that other actions trigger a click event on the button that triggers the function.
