### PR TITLE
Fix author search link

### LINKED ISSUE #3314: Filtering by author is incomplete
When clicking on the author of an article, it filters by the author but only in the main stream. It is not a problem when the feed is available in the main stream. But when the feed is not available in the main stream, there is no result returned.

What's missing is the current context on the author filter.

### PR DESCRIPTION
**Pull request by aledeg**
Closes #3314

Changes proposed in this pull request:

- fix author filter when the feed is not in the main stream

How to test the feature manually:

1. Select a feed that is not visible in the main stream
2. Click the author of an article to filter
3. There should be some results

Pull request checklist:

- [x] clear commit messages
- [x] code manually tested
- [ ] unit tests written (optional if too hard)
- [ ] documentation updated

[Additional information can be found in the documentation](https://github.com/FreshRSS/FreshRSS/tree/master/docs/en/developers/04_Pull_requests.md).

Before, when clicking on the author link, the search was done on the
main stream in the normal view. It's fine until the feed is not visible
in the main stream.
Now, the current context is used along with the search.

### CODE REVIEW

File: lib/Minz/Request.php [hunk 1]
```diff
@@ -71,6 +71,15 @@ public static function currentRequest() {
 			'params' => self::$params,
 		);
 	}
+	public static function modifiedCurrentRequest(array $extraParams = null) {
```
Comment (Alkarex) [inline lib/Minz/Request.php:74]: Good idea; I had to double-check which type-hinting was available from which PHP version (this info is apparently gone from the current PHP documentation):
http://web.archive.org/web/20200101052646/https://www.php.net/manual/en/functions.arguments.php#functions.arguments.type-declaration.types
We should remember to use it more, and then even more when we drop PHP 5.x.

File: lib/Minz/Request.php [hunk 2]
```diff
@@ -71,6 +71,15 @@ public static function currentRequest() {
...
+		$currentRequest = self::currentRequest();
+		if (is_array($extraParams)) {
+			foreach ($extraParams as $key => $value) {
```
Comment (Alkarex) [inline lib/Minz/Request.php]: Wouldn't `array_merge()` (or similar array function) work better here?

Comment (aledeg) [reply lib/Minz/Request.php]: Of course! I'll change that.

File: lib/Minz/Request.php (hunk 1 above)
Comment (Alkarex) [reply lib/Minz/Request.php:74]: Ah, moved there :-) https://php.net/language.types.declarations

Comment (Alkarex) [reply lib/Minz/Request.php:74]: About dropping PHP 5: https://github.com/FreshRSS/FreshRSS/discussions/3321
