### PR TITLE
Fix sanitize feed description

### LINKED ISSUE #3221: Unable to remove or edit feed once added.
After adding [redacted feed url] feed to FreshRSS, when I attempt to manage the feed, it processes the href link in the feeds description when I click on the edit boxes, it won't save, and I can't remove it.

### PR DESCRIPTION
**Pull request by Alkarex**
#fix https://github.com/FreshRSS/FreshRSS/issues/3221

### CODE REVIEW

**Review by aledeg — APPROVED** [review]

File: app/Models/FeedDAO.php [hunk 1]
```diff
@@ -62,7 +62,7 @@ public function addFeed($valuesTmp) {
 			$valuesTmp['category'],
 			mb_strcut(trim($valuesTmp['name']), 0, FreshRSS_DatabaseDAO::LENGTH_INDEX_UNICODE, 'UTF-8'),
 			substr($valuesTmp['website'], 0, 255),
-			mb_strcut($valuesTmp['description'], 0, 1023, 'UTF-8'),
```
Comment (Alkarex) [inline app/Models/FeedDAO.php:65]: Cutting a sanitized string might make it not sanitized anymore

File: app/views/helpers/feed/update.phtml [hunk 2]
```diff
@@ -7,7 +7,7 @@
 		<a href="<?= _url('stats', 'repartition', 'id', $this->feed->id()) ?>"><?= _i('stats') ?> <?= _t('sub.feed.stats') ?></a>
 	</div>
 
-	<p><?= $this->feed->description() ?></p>
+	<p><?= sanitizeHTML($this->feed->description()) ?></p>
```
Comment (Alkarex) [inline app/views/helpers/feed/update.phtml:10]: For existing descriptions in database, some of which might not be fully sanitized

File: lib/lib_rss.php [hunk 3]
```diff
@@ -241,16 +241,25 @@ function customSimplePie($attributes = array()) {
 	return $simplePie;
 }
 
-function sanitizeHTML($data, $base = '') {
-	if (!is_string($data)) {
+function sanitizeHTML($data, $base = '', $maxLength = false) {
```
Comment (Alkarex) [inline lib/lib_rss.php:244]: Extended this function to offer a cutting functionality
