### PR TITLE
Fix fetch preview

### LINKED ISSUE #2923: ⓘ Reload articles and fetch complete content - HTTP ERROR 500
I'm trying out selectors to pull truncated content, but I can't really tell if I'm doing it right.

I'm trying to get the complete comment thread from github issues using maybe `discussion_bucket` or `js-discussion`

no matter what I enter, if I click the eye next to that, I just get a blank popout window.. then if I go to the bottom of the page and click "Reload articles" I get http error 500.

any insight would be appreciated
thank you.

### PR DESCRIPTION
**Pull request by Alkarex**
#fix https://github.com/FreshRSS/FreshRSS/issues/2923
In MariaDB / MySQL, we cannot start a new query if we have not consumed
the previous buffered query fully.

### CODE REVIEW

File: app/Controllers/feedController.php [hunk 1]
```diff
@@ -755,8 +755,9 @@ public function contentSelectorPreviewAction() {
 
 		//Get first entry (syntax robust for Generator or Array)
 		foreach ($entries as $myEntry) {
-			$entry = $myEntry;
-			break;
```
Comment (Alkarex) [inline app/Controllers/feedController.php:759]: We must not break because we need to consume the result of the buffered query fully before starting a new one.

**Comment by Alkarex** [comment]
Ah, one more fix needed for "reload"

**Comment by Alkarex** [comment]
Done

**Review by Leepic — APPROVED** [review]
It works for me (reload + preview). Thank you!
